# Pengenalan Python
*by Raynaldi La'lang*

Start learning Python: https://www.w3schools.com/python/

# Install package dan import module

https://www.w3schools.com/python/python_pip.asp

Cara memeriksa package yang sudah ter-install

In [ ]:
!pip list

Package                       Version        
----------------------------- ---------------
absl-py                       0.8.1          
alabaster                     0.7.12         
albumentations                0.1.12         
altair                        4.1.0          
argon2-cffi                   20.1.0         
asgiref                       3.2.10         
astor                         0.8.1          
astropy                       4.0.1.post1    
astunparse                    1.6.3          
atari-py                      0.2.6          
atomicwrites                  1.4.0          
attrs                         20.1.0         
audioread                     2.1.8          
autograd                      1.3            
Babel                         2.8.0          
backcall                      0.2.0          
beautifulsoup4                4.6.3          
bleach                        3.1.5          
blis                          0.4.1          
bokeh                         2.1.

Cara install package

In [ ]:
!pip install plotly
!pip install pandas>=1.0.5

#In Jupyter Notebook
# !python -m pip install plotly

Cara import module

In [ ]:
import numpy as np
import math
from math import pi
import matplotlib.pyplot as plt

# How to use Colab

* cell
* text
* runtime
* download
* rename
* share




# Komentar

Untuk memberikan komentar, kita bisa memberikan tanda # sebagai awal komentar.
Untuk komentar dengan lebih dari satu line bisa menggunakan """ di awal dan akhir komentar

Tips: Hotkey untuk *# komentar* adalah Ctrl + /

In [ ]:
# Komentar 1
# Komentar 2
# Komentar 3

"""
This is a comment
written in
more than just one line
"""

'\nThis is a comment\nwritten in\nmore than just one line\n'

# Print

**print()** digunakan untuk mencetak suatu object

In [ ]:
x = "Hello World"
y = "WOW"
print(x)
print(y)
print(x,y)

Hello World
WOW
Hello World WOW


# If

Untuk menjalankan suatu command menurut kondisi tertentu, digunakan **if ... elif ... else**

In [ ]:
a = 33
b = 200

if b == a:
  print("b is equal to a")

elif b < a:
  print("b is less than a")
  
else:
  print("b is greater than a")

b is greater than a


# While

Perintah **while** digunakan untuk menjalankan serangkaian command selama suatu kondisi dipenuhi

In [ ]:
a = 1
b = 10

while a<10 and b>1:
  a += 1
  b = b-1

print(a)
print(b)

10
1


# Iterables dan For

**Iterable** adalah object yang dapat "di-iterasi" menggunakan **for**-loop.

In [ ]:
for i in range(5):
  print(i)

0
1
2
3
4


In [ ]:
for i in range(2,5):
  print(i)

2
3
4


In [ ]:
for i in range(2,10,3):
  print(i)

2
5
8


In [ ]:
X = ["a",None,1,True]
for x in X:
  print(x)

a
None
1
True


Suatu iterable object dapat diakses dengan [ ] (kurung siku)

Catatan: penggunaan indeks dalam Python dimulai dari 0

In [ ]:
X = [["a",None,1,True],
     [-1,2,0,5]
     ]

# mengakses satu elemen
print(X[1][2])

# mengakses beberapa elemen
print(X[1])
print(X[1][1:3])

# mengakses elemen terakhir
print(X[0][-1])

0
[-1, 2, 0, 5]
[2, 0]
True


Untuk menambahkan elemen baru ke dalam list, gunakan list.**append()**

In [ ]:
X = [1,2,3]
X.append(0)
print(X)

[1, 2, 3, 0]


# NumPy

**numpy** adalah salah satu Python package yang paling umum digunakan yang dilengkapi dengan fitur-fitur yang relatif sederhana, namun sangat berguna

https://numpy.org/doc/stable/reference/index.html

In [ ]:
import numpy as np

**numpy array** adalah object yang menyerupai list, namun memiliki keunggulan dari sisi performa dan efisiensi

In [ ]:
X = np.array([[1,0,0],
             [0,1,0],
             [0,0,1]])

print(X[1,1])

1


**numpy** juga bisa digunakan untuk membuat array of zeros, array of ones, array of random numbers, dan sequence

In [ ]:
X = np.zeros((2,3))
print(X)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
Y = np.ones((2,3,2))
print(Y)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [ ]:
Z = np.arange(1,11,3)
print(Z)

[ 1  4  7 10]


In [ ]:
R = np.random.rand(2,3,2)
print(R)

[[[0.94805836 0.92065516]
  [0.49549117 0.74549305]
  [0.89564073 0.85653393]]

 [[0.69332447 0.28963987]
  [0.3921668  0.18651856]
  [0.02954415 0.5262563 ]]]


**numpy** juga menyediakan fungsi-fungsi matematika

In [ ]:
print(np.sqrt(2))
print(np.exp(1))

X = np.array([-np.pi,1,2*np.pi])
print(np.cos(X))

1.4142135623730951
2.718281828459045
[-1.          0.54030231  1.        ]


# Lambda

**lambda** pada umumnya digunakan untuk membuat fungsi yang sederhana

In [ ]:
y = lambda x: x**2
print(y(2))

4


In [ ]:
z = lambda x,y: x*y
print(z(2,3))

6


**lambda** juga bisa digunakan untuk membuat suatu list dengan aturan tertentu

In [ ]:
f = lambda x: x**3
X = [f(x) for x in range(-2,5)]
print(X)

[-8, -1, 0, 1, 8, 27, 64]


# Function

Untuk membuat fungsi yang lebih kompleks, biasa digunakan perintah **def**

In [ ]:
def hello_world():
  print("Hello World")

hello_world()

Hello World


In [ ]:
def even_or_odd(x):
  if x % 2 == 2:
    out = "even"
  else:
    out = "odd"

  return out

print(even_or_odd(3))

odd


In [ ]:
def addition(a,b):
  return a+b

print(addition(1,3.1))

4.1


# Others

?module digunakan untuk membuka dokumentasi dari suatu imported object

In [ ]:
import numpy as np
?np

**type** digunakan untuk melihat tipe object

In [ ]:
print(type(2.))

<class 'float'>


Beberapa fungsi yang dapat digunakan untuk iterable

In [ ]:
X = np.random.rand(5)

print(X)
print(sorted(X))
print(len(X))
print(sum(X))
print(max(X))
print(min(X))

[0.93432521 0.2708278  0.95670491 0.33414479 0.82802173]
[0.270827803238763, 0.3341447854137992, 0.8280217265744824, 0.9343252118132983, 0.9567049095812753]
5
3.324024436621618
0.9567049095812753
0.270827803238763


Seperti **numpy**, **math** adalah package yang dapat digunakan untuk mengakses fungsi dan konstanta matematika yang umum digunakan.

Pada umumnya **numpy** lebih efisien, namun ada beberapa fungsi dalam **math** yang tidak tersedia di **numpy**.

Untuk fungsi-fungsi yang lebih rumit, biasa digunakan **scipy**.

https://docs.python.org/3/library/math.html

https://docs.scipy.org/doc/scipy/reference/tutorial/special.html

In [ ]:
from math import factorial
from scipy.special import j0 # zeroth order bessel function of the first kind

print(factorial(5))
print(j0(5))

120
-0.1775967713143383
